<?php

namespace CyberWolfStudio\Lingua;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Facades\File;
use JsonException;

final class CommandTranslationGenerator extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'lingua:generate {path=./resources/js/lingua.js}';

    /**
     * The console command description.
     *
     * @var string|null
     */
    protected $description = 'Generate translation js file for including in build process';

    /**
     * Filesystem instance for moving files.
     *
     * @var Filesystem
     */
    protected Filesystem $files;

    /**
     * Create a new console command instance.
     *
     * @return void
     */
    public function __construct(Filesystem $files)
    {
        parent::__construct();

        $this->files = $files;
    }

    /**
     * Process the command.
     *
     * @return void
     * @throws JsonException
     */
    public function handle(): void
    {
        $path = $this->argument('path');

        // Generate full bundle and per-locale chunks
        [$fullJs, $localesPayload] = $this->generateWithLocales();

        // Write full file (as before)
        $this->makeDirectory($path);
        $this->files->put($path, $fullJs);

        // Determine split directory (defaults to resources/js/lingua)
        $splitDir = $this->defaultSplitDir($path);
        $this->makeDirectory($splitDir . DIRECTORY_SEPARATOR . 'placeholder'); // ensure dir exists

        // Write one file per locale
        foreach ($localesPayload as $locale => $js) {
            $localeFile = $splitDir . DIRECTORY_SEPARATOR . $locale . '.js';
            $this->files->put($localeFile, $js);
        }

        $this->info('Translations file generated (full and per-locale).');
    }

    /**
     * Generate the translations for the file.
     *
     * @return string
     * @throws JsonException
     */
    public function generateWithLocales(): array
    {
        $locales = [];

        $directories = File::directories(lang_path());

        foreach ($directories as $dir) {
            $path = str_replace(lang_path() . DIRECTORY_SEPARATOR, '', $dir);
            $locales[] = $path;
        }

        $compiled = TranslationPayload::compile($locales);

        // Full JS (original behavior)
        $fullJson = $compiled->toJson();
        $fullJs = <<<EOT
const Lingua = { translations: $fullJson }

export { Lingua }

EOT;

        // Per-locale JS modules
        $localesPayload = [];
        foreach ($compiled as $locale => $payload) {
            $json = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            $localesPayload[$locale] = <<<EOT
// Auto-generated by lingua:generate
const dict = $json
export default dict
EOT;
        }

        return [$fullJs, $localesPayload];
    }

    /**
     * Resolve default directory for per-locale split files.
     */
    protected function defaultSplitDir(string $path): string
    {
        if (str_ends_with($path, '.js')) {
            // If a file path was provided, place split files under a sibling "lingua" directory
            $baseDir = dirname($path);
            return $baseDir . DIRECTORY_SEPARATOR . 'lingua';
        }

        // If a directory was provided, use it directly
        return rtrim($path, DIRECTORY_SEPARATOR);
    }

    /**
     * Make the directory if it doesn't exist.
     *
     * @param string $path
     * @return string
     */
    protected function makeDirectory(string $path): string
    {
        if (!$this->files->isDirectory(dirname($path))) {
            $this->files->makeDirectory(dirname($path), 0777, true, true);
        }

        return $path;
    }
}
